/* SPDX-License-Identifier: MIT */
#ifndef BHARAT_UAPI_DIAG_VERSION_H
#define BHARAT_UAPI_DIAG_VERSION_H

#define BH_DIAG_ABI_VERSION 1u
#define BH_DIAG_BOOT_EVIDENCE_SCHEMA_VERSION 1u
#define BH_DIAG_HEALTH_SCHEMA_VERSION 1u

#endif
