#ifndef BHARAT_ARCH_ARM64_CPU_FEATURES_H
#define BHARAT_ARCH_ARM64_CPU_FEATURES_H

// Assume ARCH_CPU_FEAT_ARCH_BASE is already defined by arch_cpu_caps.h

typedef enum {
    ARCH_CPU_FEAT_ARM64_ASIMD = ARCH_CPU_FEAT_ARCH_BASE,
    ARCH_CPU_FEAT_ARM64_LSE,
    ARCH_CPU_FEAT_ARM64_SVE,
    ARCH_CPU_FEAT_ARM64_SVE2,
    ARCH_CPU_FEAT_ARM64_PMULL,
    ARCH_CPU_FEAT_ARM64_SHA1,
    ARCH_CPU_FEAT_ARM64_SHA2,
    ARCH_CPU_FEAT_ARM64_AES,
    ARCH_CPU_FEAT_ARM64_CRC32,

    ARCH_CPU_FEAT_TARGET__COUNT
} arch_arm64_cpu_feature_t;

#endif // BHARAT_ARCH_ARM64_CPU_FEATURES_H
