# BharatComponentPolicy.cmake
# Resolve and validate driver/service/subsystem selections from profile/personality/board.

function(bharat_component_option name default_value description)
    if(NOT DEFINED ${name})
        set(${name} ${default_value} CACHE BOOL "${description}")
    else()
        set(${name} ${${name}} CACHE BOOL "${description}" FORCE)
    endif()
endfunction()

function(bharat_require_component option_name reason)
    if(NOT ${option_name})
        message(FATAL_ERROR "${option_name}=OFF is invalid for this target: ${reason}")
    endif()
endfunction()

function(bharat_apply_component_policy)
    # Baseline defaults
    bharat_component_option(BHARAT_ENABLE_DRIVER_NET ON "Build networking drivers")

    # Serial driver defaults
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_NS16550 OFF "Build NS16550 serial driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_PL011 OFF "Build PL011 serial driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_SIFIVE OFF "Build SiFive UART driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_CADENCE OFF "Build Cadence UART driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_IMX_LPUART OFF "Build NXP i.MX LPUART driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SERIAL_DW_APB OFF "Build DesignWare APB UART driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_ACCEL ON "Build accelerator drivers")
    bharat_component_option(BHARAT_ENABLE_DRIVER_CLUSTER_BUS ON "Build cluster bus drivers")
    bharat_component_option(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN OFF "Build automotive CAN driver")
    # Per-driver overrides (default to legacy group flags for compatibility)
    bharat_component_option(BHARAT_ENABLE_DRIVER_VIRTIO_NET ${BHARAT_ENABLE_DRIVER_NET} "Build virtio-net driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_PTP_CLOCK ${BHARAT_ENABLE_DRIVER_NET} "Build ptp-clock driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_FPGA_MGR ${BHARAT_ENABLE_DRIVER_ACCEL} "Build fpga manager driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ${BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN} "Build CAN loopback driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_CAN_CORE ${BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN} "Build CAN generic core driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_VIRT_CAN ${BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN} "Build virt_can virtual controller")
    bharat_component_option(BHARAT_ENABLE_SERVICE_CAN ${BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN} "Build CAN user-space service")
    bharat_component_option(BHARAT_ENABLE_DRIVER_GENERIC_REGISTRY ON "Build generic driver registry")
    bharat_component_option(BHARAT_ENABLE_DRIVER_ARCH_IRQ_TIMER ON "Build arch IRQ/timer generic driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_BOARD_FABRIC ON "Build board fabric generic driver")

    # New storage, bus, and sensor defaults
    bharat_component_option(BHARAT_ENABLE_DRIVER_NVME OFF "Build NVMe driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SDHOST OFF "Build SD/eMMC host driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_I2C_CORE OFF "Build I2C core driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_SPI_CORE OFF "Build SPI core driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_VIRTIO_INPUT OFF "Build virtio input driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_I2C_HID OFF "Build I2C HID driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_IMU OFF "Build Generic IMU driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_DRM_CORE OFF "Build DRM core driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_VIRTIO_GPU OFF "Build virtio GPU driver")

    bharat_component_option(BHARAT_ENABLE_SUBSYS_LINUX ON "Build Linux personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_WINDOWS ON "Build Windows personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_ANDROID OFF "Build Android personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE OFF "Build automotive subsystem")

    bharat_component_option(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD ON "Build boot display daemon")
    bharat_component_option(BHARAT_ENABLE_SERVICE_NETWORK ON "Build network services")

    bharat_component_option(BHARAT_ENABLE_UI ON "Build user-space UI subdirectories")
    bharat_component_option(BHARAT_ENABLE_FBUI ON "Build Framebuffer UI component")

    set(_profile "${BHARAT_DEVICE_PROFILE}")
    set(_personality "${BHARAT_PERSONALITY_PROFILE}")
    string(TOLOWER "${BHARAT_TARGET_BOARD}" _board)

    # Resolve Arch-based Default Serial Drivers
    if(BHARAT_ARCH_FAMILY MATCHES "X86")
        set(BHARAT_ENABLE_DRIVER_SERIAL_NS16550 ON CACHE BOOL "Build NS16550 serial driver" FORCE)
    elseif(BHARAT_ARCH_FAMILY MATCHES "ARM")
        set(BHARAT_ENABLE_DRIVER_SERIAL_PL011 ON CACHE BOOL "Build PL011 serial driver" FORCE)
    elseif(BHARAT_ARCH_FAMILY MATCHES "RISCV")
        set(BHARAT_ENABLE_DRIVER_SERIAL_SIFIVE ON CACHE BOOL "Build SiFive UART driver" FORCE)
        # Often also need NS16550 for qemu-virt
        set(BHARAT_ENABLE_DRIVER_SERIAL_NS16550 ON CACHE BOOL "Build NS16550 serial driver" FORCE)
    endif()

    if(_profile STREQUAL "AUTOMOTIVE_ECU")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_CORE ON CACHE BOOL "Build CAN generic core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_VIRT_CAN ON CACHE BOOL "Build virt_can virtual controller" FORCE)
        set(BHARAT_ENABLE_SERVICE_CAN ON CACHE BOOL "Build CAN user-space service" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
        set(BHARAT_ENABLE_SERVICE_NETWORK OFF CACHE BOOL "Build network services" FORCE)
        set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD OFF CACHE BOOL "Build boot display daemon" FORCE)
        set(BHARAT_ENABLE_DRIVER_I2C_CORE ON CACHE BOOL "Build I2C core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SPI_CORE ON CACHE BOOL "Build SPI core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SERIAL_CADENCE ON CACHE BOOL "Build Cadence UART driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SERIAL_DW_APB ON CACHE BOOL "Build DesignWare APB UART driver" FORCE)
    elseif(_profile STREQUAL "AUTOMOTIVE_INFOTAINMENT")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_CORE ON CACHE BOOL "Build CAN generic core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_VIRT_CAN ON CACHE BOOL "Build virt_can virtual controller" FORCE)
        set(BHARAT_ENABLE_SERVICE_CAN ON CACHE BOOL "Build CAN user-space service" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
        set(BHARAT_ENABLE_SERVICE_NETWORK ON CACHE BOOL "Build network services" FORCE)
        set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD ON CACHE BOOL "Build boot display daemon" FORCE)
        set(BHARAT_ENABLE_SUBSYS_ANDROID ON CACHE BOOL "Build Android personality subsystem" FORCE)
        set(BHARAT_ENABLE_DRIVER_DRM_CORE ON CACHE BOOL "Build DRM core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_I2C_HID ON CACHE BOOL "Build I2C HID driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SDHOST ON CACHE BOOL "Build SD/eMMC host driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SERIAL_CADENCE ON CACHE BOOL "Build Cadence UART driver" FORCE)
    elseif(_profile STREQUAL "DRONE" OR _profile STREQUAL "ROBOTICS")
        set(BHARAT_ENABLE_DRIVER_I2C_CORE ON CACHE BOOL "Build I2C core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SPI_CORE ON CACHE BOOL "Build SPI core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_IMU ON CACHE BOOL "Build Generic IMU driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_SERIAL_IMX_LPUART ON CACHE BOOL "Build NXP i.MX LPUART driver" FORCE)
    elseif(_profile STREQUAL "CLOUD" OR _profile STREQUAL "DATACENTER")
        set(BHARAT_ENABLE_DRIVER_NVME ON CACHE BOOL "Build NVMe driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_VIRTIO_INPUT ON CACHE BOOL "Build virtio input driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_VIRTIO_GPU ON CACHE BOOL "Build virtio GPU driver" FORCE)
    elseif(_profile STREQUAL "DESKTOP")
        if(BHARAT_BOOT_GUI)
            set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD ON CACHE BOOL "Build boot display daemon" FORCE)
            set(BHARAT_ENABLE_UI ON CACHE BOOL "Build user-space UI" FORCE)
            set(BHARAT_ENABLE_FBUI ON CACHE BOOL "Build Framebuffer UI" FORCE)
            set(BHARAT_UI_LVGL ON CACHE BOOL "Enable LVGL adapter and core" FORCE)
        else()
            set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD OFF CACHE BOOL "Build boot display daemon" FORCE)
            set(BHARAT_ENABLE_UI OFF CACHE BOOL "Build user-space UI" FORCE)
            set(BHARAT_ENABLE_FBUI OFF CACHE BOOL "Build Framebuffer UI" FORCE)
            set(BHARAT_UI_LVGL OFF CACHE BOOL "Enable LVGL adapter and core" FORCE)
        endif()
        # Ensure the architecture-specific UARTs are definitely enabled
        if(BHARAT_ARCH_FAMILY MATCHES "X86")
            set(BHARAT_ENABLE_DRIVER_SERIAL_NS16550 ON CACHE BOOL "Build NS16550 serial driver" FORCE)
            set(BHARAT_ENABLE_DRIVER_VIDEO_BOCHS ON CACHE BOOL "Build Bochs VGA driver" FORCE)
        elseif(BHARAT_ARCH_FAMILY MATCHES "ARM")
            set(BHARAT_ENABLE_DRIVER_SERIAL_PL011 ON CACHE BOOL "Build PL011 serial driver" FORCE)
            set(BHARAT_ENABLE_DRIVER_VIDEO_VIRTIO_GPU ON CACHE BOOL "Build VirtIO-GPU driver" FORCE)
        elseif(BHARAT_ARCH_FAMILY MATCHES "RISCV")
            set(BHARAT_ENABLE_DRIVER_SERIAL_NS16550 ON CACHE BOOL "Build NS16550 serial driver" FORCE)
            set(BHARAT_ENABLE_DRIVER_VIDEO_VIRTIO_GPU ON CACHE BOOL "Build VirtIO-GPU driver" FORCE)
        endif()
    endif()

    if(_board MATCHES "ecu")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_CORE ON CACHE BOOL "Build CAN generic core driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_VIRT_CAN ON CACHE BOOL "Build virt_can virtual controller" FORCE)
        set(BHARAT_ENABLE_SERVICE_CAN ON CACHE BOOL "Build CAN user-space service" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
    endif()

    if(_personality STREQUAL "LINUX")
        set(BHARAT_ENABLE_SUBSYS_LINUX ON CACHE BOOL "Build Linux personality subsystem" FORCE)
    elseif(_personality STREQUAL "ANDROID")
        set(BHARAT_ENABLE_SUBSYS_LINUX ON CACHE BOOL "Build Linux personality subsystem" FORCE)
        set(BHARAT_ENABLE_SUBSYS_ANDROID ON CACHE BOOL "Build Android personality subsystem" FORCE)
    elseif(_personality STREQUAL "WINDOWS")
        set(BHARAT_ENABLE_SUBSYS_WINDOWS ON CACHE BOOL "Build Windows personality subsystem" FORCE)
    elseif(_personality STREQUAL "MAC")
        # No dedicated subsystem target yet.
    elseif(_personality STREQUAL "NATIVE")
        # Keep defaults.
    else()
        message(FATAL_ERROR "Unsupported BHARAT_PERSONALITY_PROFILE='${BHARAT_PERSONALITY_PROFILE}'")
    endif()

    # Required component checks
    if(_profile STREQUAL "AUTOMOTIVE_ECU")
        bharat_require_component(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN "AUTOMOTIVE_ECU requires CAN driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK "AUTOMOTIVE_ECU requires CAN loopback driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_CORE "AUTOMOTIVE_ECU requires CAN generic core driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_VIRT_CAN "AUTOMOTIVE_ECU requires virt_can virtual controller")
        bharat_require_component(BHARAT_ENABLE_SERVICE_CAN "AUTOMOTIVE_ECU requires CAN user-space service")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE "AUTOMOTIVE_ECU requires automotive subsystem")
    elseif(_profile STREQUAL "AUTOMOTIVE_INFOTAINMENT")
        bharat_require_component(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN "AUTOMOTIVE_INFOTAINMENT requires CAN driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK "AUTOMOTIVE_INFOTAINMENT requires CAN loopback driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_CORE "AUTOMOTIVE_INFOTAINMENT requires CAN generic core driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_VIRT_CAN "AUTOMOTIVE_INFOTAINMENT requires virt_can virtual controller")
        bharat_require_component(BHARAT_ENABLE_SERVICE_CAN "AUTOMOTIVE_INFOTAINMENT requires CAN user-space service")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE "AUTOMOTIVE_INFOTAINMENT requires automotive subsystem")
        bharat_require_component(BHARAT_ENABLE_SERVICE_NETWORK "AUTOMOTIVE_INFOTAINMENT requires network services")
        bharat_require_component(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD "AUTOMOTIVE_INFOTAINMENT requires boot display")
    endif()

    if(_personality STREQUAL "LINUX")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_LINUX "LINUX personality requires Linux subsystem")
    elseif(_personality STREQUAL "ANDROID")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_LINUX "ANDROID personality requires Linux subsystem")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_ANDROID "ANDROID personality requires Android subsystem")
    elseif(_personality STREQUAL "WINDOWS")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_WINDOWS "WINDOWS personality requires Windows subsystem")
    endif()

    if(BHARAT_ENABLE_FBUI)
        bharat_require_component(BHARAT_ENABLE_UI "FBUI requires UI components enabled")
    endif()

    message(STATUS "Component policy resolved for profile=${BHARAT_DEVICE_PROFILE}, personality=${BHARAT_PERSONALITY_PROFILE}, board=${BHARAT_TARGET_BOARD}")
endfunction()
